name: ratt
channels:
  - conda-forge
  - fastai
  - pytorch
  - defaults
dependencies:
  - python=3.8
#  - torch=1.4.0
#  - attr=0.3.1
#  - dacite=1.5.0 # sta su pip
#  - nlg_eval=2.3
#  - rouge_score=0.0.3
  - torchvision=0.5.0
  - numpy=1.18.1
  - pandas=1.0.3
  - Pillow=7.2.0
  - h5py=2.10.0
  - matplotlib=3.1.3
  - seaborn=0.10.1
  - bidict=0.19.0
  - nltk=3.4.5
  - pycocotools=2.0.0
  - tqdm=4.43.0
  - attrs=19.3.0
  - dataclasses=0.7
  - ipython